#!/usr/bin/env python3
"""Bake real compile artifacts from hello_sample.py → playground_artifacts.py."""

from __future__ import annotations

from pathlib import Path

from ourui.pipeline import dump_json, emit_all

ROOT = Path(__file__).resolve().parent
SAMPLE = ROOT / "hello_sample.py"
OUT = ROOT / "playground_artifacts.py"


def main() -> None:
    sample_src = SAMPLE.read_text(encoding="utf-8")
    bundle = emit_all(SAMPLE, title="Hello")
    ast_json = dump_json(SAMPLE)

    body = "\n".join(
        [
            '"""AUTO-GENERATED by bake_artifacts.py — do not edit by hand."""',
            "",
            f"SAMPLE_SOURCE = {sample_src!r}",
            f"HTML_OUT = {bundle['html']!r}",
            f"JS_OUT = {bundle['js']!r}",
            f"CSS_OUT = {bundle['css']!r}",
            f"AST_OUT = {ast_json!r}",
            "",
        ]
    )
    OUT.write_text(body, encoding="utf-8")
    print(
        f"wrote {OUT.name}: html={len(bundle['html'])} "
        f"js={len(bundle['js'])} css={len(bundle['css'])} ast={len(ast_json)}"
    )


if __name__ == "__main__":
    main()
